name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check-translations:
    name: Check Translations
    # Linux is required since this is a docker container action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: check_translations
        uses: ashutoshgngwr/android-translations@v1
        with:
          projectDir: ./
      - name: Add comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: 1
          body: ${{ steps.check_translations.outputs.report }}
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: bash ./gradlew build
